/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Design = IDL.Record({
  'style' : IDL.Text,
  'timestamp' : Time,
  'roomType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'getDesignHistorySorted' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'getDesignsByRoomType' : IDL.Func([IDL.Text], [IDL.Vec(Design)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Design = IDL.Record({
    'style' : IDL.Text,
    'timestamp' : Time,
    'roomType' : IDL.Text,
  });
  
  return IDL.Service({
    'addDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'getDesignHistorySorted' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'getDesignsByRoomType' : IDL.Func([IDL.Text], [IDL.Vec(Design)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };